I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 25, in script
    show papa_cstl width 400
Exception: Image 'papa_cstl' does not accept attributes 'width 400'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 25, in script
    show papa_cstl width 400
  File "/opt/renpy-8.2.1-sdk/renpy/ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/opt/renpy-8.2.1-sdk/renpy/ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "/opt/renpy-8.2.1-sdk/renpy/exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/opt/renpy-8.2.1-sdk/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/opt/renpy-8.2.1-sdk/renpy/display/displayable.py", line 246, in _duplicate
    args.extraneous()
  File "/opt/renpy-8.2.1-sdk/renpy/display/displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'papa_cstl' does not accept attributes 'width 400'.

Linux-6.5.0-35-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.2.1.24030407
CSTL 1.0
Wed May 15 11:12:08 2024
